### ISSUE TITLE
Infinite data stream with volume peaks 

### ISSUE THREAD

**Issue by chook** [tdunning/log-synth#42]
I was wondering if it’s possible to run the application constantly, rolling the file every X minutes (in conjunction with fluentd)
with “random” bursts 

my aim is to mimic even more realistic data pipelines

**Comment by tdunning** [comment]
Any thoughts about what I suggested?

**Comment by chook** [comment]
Hey @tdunning sorry for not replying sooner - I did read through this, said to myself "wow this is an extensive reply" but at the same time I ended up pursuing something a bit different for my use case.

I understand the characteristics of what you explained and that it's not entirely log-synth responsibility to generate data continuously.

thank you for a great project!

**Comment by tdunning** [comment]
Just for my own education, can you say a bit about what approach you eventually took? 

And what it was that led you there?

Thanks!

**Comment by chook** [comment]
sure thing, would be happy to share. 
I took https://github.com/GoogleCloudPlatform/microservices-demo and deployed it on a kubernetes cluster while making a few changes:
1. changed the locust file to generate more load with a double wave pattern (https://github.com/locustio/locust/blob/master/examples/custom_shape/double_wave.py) 
2. Edited the structured logs to be a bit less structured and more similar to traditional logging (user X did Y and got response Z)
3. changed locust a bit to have some terminal paths to cause errors
4. Added more logging, with more verbosity with some random error conditions.
5. Changed parts of the code to use faker libraries (e.g. random credit card, address, email, etc)

It helped me to have a live project of a known app (e-commerce) to talk about its logging needs and pitfalls.

If you'd like to speak more, I would be happy to have virtual lunch sometime. my email is chen at coralogix dot com

**Comment by tdunning** [comment]
OK. Cool. And thanks for the ideas for improvement.

It isn't python, but you can arrange to sample any of the samplers as a
real-time service with log-synth. This could include everything you have
here because none of it involves state and would be callable from python.
It could be easily adapted to delay the response according to a real time
randomized rate constraint.

I will file an issue to build an example of such a service and explain the
limitations. My guess is that what you have is more congenial to you
because of language choice (python instead of Java).

**Comment by chook** [comment]
I'm a Java person (X co-founder of overops.com) :D 
I'd love to revisit this in the future.

**Comment by tdunning** [comment]
Back burner for now, but could be cool.
